### ISSUE TITLE
批量添加主机有bug

### ISSUE THREAD

**Issue by Ethswam** [tp4a/teleport#100]
1 批量添加主机的模板与官网的图片不一致，有时间更新一下

2 批量添加后，发现csv模板中的用户名和密码内容无法添加成功，虽然已经完全参照新模板里面示例。新模板里面用ssh，官网给的老模板图片显示用 数字2

**Comment by apexliu** [comment]
1. 嗯，网站上的文档需要更新；
2. 新的模板中，主机和账号要在不同的行上才能正确区分，这一点要注意一下。

**Comment by apexliu** [comment]
已经更新了文档。 https://docs.tp4a.com

**Comment by sansam** [comment]
刚踩到没看doc的锅..
