### ISSUE TITLE
请问下面这个截图里的shell用的什么字体

### ISSUE THREAD

**Issue by tuhaolam** [tp4a/teleport#106]
![image](https://user-images.githubusercontent.com/10894348/45801163-9a79b400-bce5-11e8-9b8c-4a73bdfd530f.png)

**Comment by apexliu** [comment]
Monaco, comes from MacOS.

**Comment by tuhaolam** [comment]
感谢，已经搞定了ubuntu+windows环境的字体配置，附送下字体下载地址：
http://www.pc6.com/softview/SoftView_63809.html#download
https://github.com/cstrap/monaco-font
