### ISSUE TITLE
连接控制->会话超时，这个时间设置，无法设置成 ‘0’

### ISSUE THREAD

**Issue by lifw555** [tp4a/teleport#132]
![image](https://user-images.githubusercontent.com/2245040/50461825-34738b80-09bc-11e9-86b2-4209d2f027bd.png)

**Comment by lifw555** [comment]
![image](https://user-images.githubusercontent.com/2245040/50461849-6389fd00-09bc-11e9-9550-5c4f1608e4ec.png)

**Comment by apexliu** [comment]
已修复，下一次发布时可验证。

**Comment by leslieDD** [comment]
teleport 会话超时设置 ，不会生效，
设置成0或者60，SSH连接上后，一小段时间没有操作，没有几分钟就断开了
-------------------------------------------------
WEB服务配置
WEB服务版本：  3.2.2
数据库类型：  SQLite
数据库文件：  /usr/local/teleport/data/db/teleport.db
与核心服务通讯地址：  http://127.0.0.1:52080/rpc
核心服务配置
核心服务版本： 3.2.0
与WEB服务通讯地址： http://127.0.0.1:7190/rpc
RDP 端口： xxx
SSH 端口： xxx
TELNET 端口：  xxx
录像文件路径： /usr/local/teleport/data/replay
