### ISSUE TITLE
bug:想了想，还是提上来把，虽然你知道----强制中断失效

### ISSUE THREAD

**Issue by yutons** [tp4a/teleport#139]
强制中断失效
![1 k0j 0_p gf7vwiobggua](https://user-images.githubusercontent.com/25010191/50536247-596b2880-0b8d-11e9-800c-cf0534ede30b.png)
![pny9 njz e7 v7x b_9](https://user-images.githubusercontent.com/25010191/50536248-5a9c5580-0b8d-11e9-839e-e58f20386973.png)
![5 a s5wd3_2 m6f9p gv](https://user-images.githubusercontent.com/25010191/50536249-5bcd8280-0b8d-11e9-972b-804b5fe9d76f.png)

**Comment by d9394** [comment]
tpcore是哪个版本？菜单左边有显示的，3.2.0以前的是有这个问题，3.2.0起已修复

**Comment by apexliu** [comment]
已经在 e58ca64e3f01b14c645896512419853dd381be2d 修复。
