### ISSUE TITLE
官方网站显示最新版本到3.2.2，是不再维护更新了么？

### ISSUE THREAD

**Issue by longren610** [tp4a/teleport#277]
官方网站显示最新版本到3.2.2，github上beta3.5.5，已经是2021年的了，是不再维护更新了么？如果是，真可惜，只能用国外的了。3.2.2版本连接windows只成功了一次，就这唯一的一次，复制粘贴还是不能用的，之后再也没成功过。

**Comment by kepy909** [comment]
你国外用的哪个？

**Comment by apexliu** [comment]
没来得及更新官网，着急用的话可以到QQ群文件中下载新版。3.6.x了都。

**Comment by apexliu** [comment]
官网已更新。
