### ISSUE TITLE
3.0.0.3版本nginx前置下的https有问题

### ISSUE THREAD

**Issue by triblewinn** [tp4a/teleport#59]
nginx+teleport，3.0.0.3 
 
1 . 在https下，火狐、edge不能识别助手，谷歌能识别。
2 . 在https下都不能播放回放。
3 . http下都正常

**Comment by apexliu** [comment]
你的nginx和TP是部署在同一台主机上的吗？

**Comment by apexliu** [comment]
找到问题了。目前助手提供的本地web接口（供页面调用，来启动本地客户端的），仅提供了http，没有提供https，而火狐和edge不允许一个https网页中进行http的ajax请求，导致无法访问助手。我会想办法解决。

**Comment by apexliu** [comment]
已经在助手中加入对https的支持。
