### ISSUE TITLE
希望能提供Linux的客户端

### ISSUE THREAD

**Issue by vperson** [tp4a/teleport#77]
对于很多互联网公司，由于涉及到版权问题，所以不使用windows操作系统，但是mac电脑对于这些公司可能又太贵了，所以公司鼓励使用Ubuntu操作系统或者centos操作系统写代码，但是teleport没有linux的客户端。

**Comment by Aaron0-wang** [comment]
我们也有此需求

**Comment by xs5816** [comment]
可以用wine跑，写个shell文件，改成exe后缀，然后可以在内部调用linux的终端
#!/bin/bash
exec deepin-terminal -e sshpass -p (这里是账号的密码，后面ssh命令的参数) $3 $4 $5 $6

**Comment by jiaxinxuan** [comment]
怎么感觉不支持Linux的软件，一般都是国产的
